version: '3'

services:
  rstudio:
    build:
      dockerfile: Dockerfile
    container_name: rstudio
    ports:
      - 8787:8787
    environment:
      #PASSWORD: passw0rd
      TZ: Asia/Tokyo
      DISABLE_AUTH: true
    volumes:
      - ./R:/home/rstudio
    tty: true
